# Generated by Django 2.2 on 2022-02-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cards',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cards',
            name='desc',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cards',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
